;;
(eval-when-compile (require 'cl))

;;;;;;;; Packages Import
(require 'coldnew-macro)
(require 'coldnew-functions)
(require 'coldnew-commands)
(require 'coldnew-variables)
(require 'coldnew-evil)
(require 'coldnew-anything)
(require 'coldnew-buffer)
(require 'coldnew-project)
(require 'coldnew-editor)


;;;;;;;; Normal Map
(when (featurep 'evil)
  (define-key evil-normal-state-map (kbd "C-x C-b") 'ibuffer)
  (when (featurep 'eproject)
    (define-key evil-normal-state-map (kbd "C-c C-b") 'eproject-ibuffer))
  (define-key evil-normal-state-map (kbd "C-x f") 'anything-find-files)
  (define-key evil-normal-state-map (kbd "C-x C-f") 'lusty-file-explorer)
  (define-key evil-normal-state-map (kbd "M-x") 'anything-M-x)
  (define-key evil-normal-state-map (kbd "C-M-X") 'smex)
  (define-key evil-normal-state-map (kbd "C-c C-e") 'eval-and-replace)
  (define-key evil-normal-state-map (kbd "C-x C-s") 'save-buffer-always)
  (define-key evil-normal-state-map (kbd "C-=") 'text-scale-increase)
  (define-key evil-normal-state-map (kbd "C-+") 'text-scale-increase)
  (define-key evil-normal-state-map (kbd "C--") 'text-scale-decrease)
  (define-key evil-normal-state-map (kbd "<f4>") 'shell-pop)
  (define-key evil-normal-state-map (kbd "C-x <f4>") 'switch-to-terminal)
  (define-key evil-normal-state-map (kbd "C-x M-s") 'egg-status)
  (define-key evil-normal-state-map (kbd "C-x M-l") 'egg-log)
  (define-key evil-normal-state-map (kbd "C-;") 'iedit-mode)
  (define-key evil-normal-state-map (kbd "u")   'undo-tree-undo)
  (define-key evil-normal-state-map (kbd "C-r") 'undo-tree-redo)
  (define-key evil-normal-state-map (kbd "M-p") 'anything-show-kill-ring)
  (define-key evil-normal-state-map (kbd "C-x M-S") 'scratch-toggle)
  (define-key evil-normal-state-map (kbd "C-x M-i") 'ielm-toggle)
  (define-key evil-normal-state-map (kbd "<f1>") 'woman)
  (define-key evil-normal-state-map (kbd "K") 'anything-man-woman)
  (define-key evil-normal-state-map (kbd "C-x C-r") 'sudo-edit)
  (define-key evil-normal-state-map (kbd "M-g") 'goto-line)
  (when (require 'buffer-toggle)
    (define-key evil-normal-state-map (kbd "C-6") 'buffer-toggle))
  (when (featurep 'ace-jump-mode)
    (define-key evil-normal-state-map (kbd "M-l") 'ace-jump-line-mode)
    (define-key evil-normal-state-map (kbd "M-w") 'ace-jump-word-mode)
    (define-key evil-normal-state-map (kbd "M-c") 'ace-jump-char-mode)
    (define-key evil-normal-state-map (kbd "M-f") 'ace-jump-char-smae-line-mode))
  )

;;;;;;;; Insert Map
(when (featurep 'evil)
  (define-key evil-insert-state-map (kbd "C-x C-b") 'ibuffer)
  (when (featurep 'eproject)
    (define-key evil-insert-state-map (kbd "C-c C-b") 'eproject-ibuffer))
  (define-key evil-insert-state-map (kbd "C-x C-f") 'lusty-file-explorer)
  (define-key evil-insert-state-map (kbd "M-x") 'anything-M-x)
  (define-key evil-insert-state-map (kbd "C-c C-e") 'eval-and-replace)
  (define-key evil-insert-state-map (kbd "C-x C-s") 'save-buffer-always)
  (define-key evil-insert-state-map (kbd "C-=") 'text-scale-increase)
  (define-key evil-insert-state-map (kbd "C-+") 'text-scale-increase)
  (define-key evil-insert-state-map (kbd "C--") 'text-scale-decrease)

  (define-key evil-insert-state-map (kbd "C-x <f4>") 'switch-to-terminal)
  (define-key evil-insert-state-map (kbd "C-x M-s") 'egg-status)
  (define-key evil-insert-state-map (kbd "C-x M-l") 'egg-log)
  (define-key evil-insert-state-map (kbd "<backspace>") 'hungry-delete-backward)
  (define-key evil-insert-state-map (kbd "<delete>") 'hungry-delete-forward)
  (define-key evil-insert-state-map (kbd "C-n") 'auto-complete)
  (define-key evil-insert-state-map (kbd "C-p") 'auto-complete)
  (define-key evil-insert-state-map (kbd "C-x M-S") 'scratch-toggle)
  (define-key evil-insert-state-map (kbd "C-x M-i") 'ielm-toggle)
  (define-key evil-insert-state-map (kbd "<f1>") 'woman)
  (define-key evil-insert-state-map (kbd "C-u") 'universal-argument)
  (define-key evil-insert-state-map (kbd "C-x C-r") 'sudo-edit)
  )

;;;;;;; Visual Map
(when (featurep 'evil)
  (when (featurep 'iedit)
    (define-key evil-visual-state-map (kbd "C-;") 'iedit-mode))
  (when (featurep 'wrap-region)
    (define-key evil-visual-state-map (kbd "<") 'wrap-region-trigger)
    (define-key evil-visual-state-map (kbd "[") 'wrap-region-trigger)
    (define-key evil-visual-state-map (kbd "{") 'wrap-region-trigger)
    (define-key evil-visual-state-map (kbd "(") 'wrap-region-trigger)
    (define-key evil-visual-state-map (kbd "'") 'wrap-region-trigger)
    (define-key evil-visual-state-map (kbd "\"") 'wrap-region-trigger))
  )

;;;;;;;; Window Map
(when (featurep 'evil)
  (define-key evil-window-map  (kbd "f") 'fullscreen-window)
  (define-key evil-window-map  (kbd "C-f") 'fullscreen-window)
  (define-key evil-window-map  (kbd "C-j") 'windmove-down-fullscreen)
  (define-key evil-window-map  (kbd "C-h") 'windmove-left-fullscreen)
  (define-key evil-window-map  (kbd "C-l") 'windmove-right-fullscreen)
  (define-key evil-window-map  (kbd "C-k") 'windmove-up-fullscreen)
  (define-key evil-window-map  (kbd "C-v") 'split-window-vertically)
  (define-key evil-window-map  (kbd "C-h") 'split-window-horizontally)
  (define-key evil-window-map  (kbd "C-n") 'make-frame)
  (define-key evil-window-map  (kbd "C-d") 'delete-frame)
  (define-key evil-window-map  (kbd "C-o") 'other-frame)
  (define-key evil-window-map  (kbd "C-a") 'delete-other-frames)
  (define-key evil-window-map  (kbd "C-s") 'sr-speedbar-toggle)
  )

;;;;;;;; Replace Map
(when (featurep 'evil)
  (define-key evil-replace-state-map (kbd "M-l") 'downcase-word)
  (define-key evil-replace-state-map (kbd "M-u") 'upcase-word)
  (define-key evil-replace-state-map (kbd "M-c") 'capitalize-word)
  )

;;;;;;;; Emacs Map
(global-set-key (kbd "<f1>") 'woman)
(global-set-key (kbd "<f4>") 'shell-pop)
(global-set-key (kbd "C-x <f4>") 'switch-to-terminal)
(global-set-key (kbd "C-+") 'text-scale-increase)
(global-set-key (kbd "C--") 'text-scale-decrease)
(global-set-key (kbd "C-=") 'text-scale-increase)
(global-set-key (kbd "C-M-X") 'smex)
(global-set-key (kbd "C-c C-e") 'eval-and-replace)
(global-set-key (kbd "C-x C-b") 'ibuffer)
(global-set-key (kbd "C-x C-s") 'save-buffer-always)
(global-set-key (kbd "C-x M-l") 'egg-log)
(global-set-key (kbd "C-x M-s") 'egg-status)
(global-set-key (kbd "M-x") 'anything-M-x)
(global-set-key (kbd "C-x M-S") 'scratch-toggle)
(global-set-key (kbd "C-x M-i") 'ielm-toggle)
(global-set-key (kbd "C-x C-r") 'sudo-edit)


(provide 'coldnew-keybinding)
;; coldnew-keybinding.el ends here.
