;;
(eval-when-compile (require 'cl))

;;;;;;;; Packages Import
(require 'coldnew-macro)
(require 'coldnew-functions)
(require 'coldnew-commands)
(require 'coldnew-variables)
(require 'coldnew-vim)
(require 'coldnew-anything)

;; (require 'popup-kill-ring)

;;;;;;;; Normal Map
(define-key evil-normal-state-map (kbd "C-x C-b") 'ibuffer)
(define-key evil-normal-state-map (kbd "C-x f") 'anything-find-files)
(define-key evil-normal-state-map (kbd "C-x C-f") 'lusty-file-explorer)
(define-key evil-normal-state-map (kbd "M-x") 'anything-M-x)
(define-key evil-normal-state-map (kbd "C-M-X") 'smex)
(define-key evil-normal-state-map (kbd "C-c C-e") 'eval-and-replace)
(define-key evil-normal-state-map (kbd "C-x C-s") 'save-buffer-always)
(define-key evil-normal-state-map (kbd "C-=") 'text-scale-increase)
(define-key evil-normal-state-map (kbd "C-+") 'text-scale-increase)
(define-key evil-normal-state-map (kbd "C--") 'text-scale-decrease)
(define-key evil-normal-state-map (kbd "<f4>") 'shell-pop)
(define-key evil-normal-state-map (kbd "C-x <f4>") 'switch-to-terminal)
(define-key evil-normal-state-map (kbd "C-x M-s") 'egg-status)
(define-key evil-normal-state-map (kbd "C-x M-l") 'egg-log)
(define-key evil-normal-state-map (kbd "C-;") 'iedit-mode)
(define-key evil-normal-state-map (kbd "u")   'undo-tree-undo)
(define-key evil-normal-state-map (kbd "C-r") 'undo-tree-redo)
(define-key evil-normal-state-map (kbd "M-p") 'anything-show-kill-ring)
(define-key evil-normal-state-map (kbd "M-K") 'sdcv-search-pointer+)
(define-key evil-normal-state-map (kbd "C-x M-S") 'scratch-toggle)
(define-key evil-normal-state-map (kbd "C-x M-i") 'ielm-toggle)
(define-key evil-normal-state-map (kbd "<f1>") 'woman)
(define-key evil-normal-state-map (kbd "K") 'anything-man-woman)
(define-key evil-normal-state-map (kbd "C-x C-r") 'sudo-edit)
(define-key evil-normal-state-map (kbd "M-g") 'goto-line)

;;;;;;;; Insert Map
(define-key evil-insert-state-map (kbd "C-x C-b") 'ibuffer)
(define-key evil-insert-state-map (kbd "C-x C-f") 'lusty-file-explorer)
(define-key evil-insert-state-map (kbd "M-x") 'anything-M-x)
(define-key evil-insert-state-map (kbd "C-c C-e") 'eval-and-replace)
(define-key evil-insert-state-map (kbd "C-x C-s") 'save-buffer-always)
(define-key evil-insert-state-map (kbd "C-=") 'text-scale-increase)
(define-key evil-insert-state-map (kbd "C-+") 'text-scale-increase)
(define-key evil-insert-state-map (kbd "C--") 'text-scale-decrease)
(define-key evil-insert-state-map (kbd "<f4>") 'shell-pop)
(define-key evil-insert-state-map (kbd "C-x <f4>") 'switch-to-terminal)
(define-key evil-insert-state-map (kbd "C-x M-s") 'egg-status)
(define-key evil-insert-state-map (kbd "C-x M-l") 'egg-log)
(define-key evil-insert-state-map (kbd "<backspace>") 'hungry-delete-backward)
(define-key evil-insert-state-map (kbd "<delete>") 'hungry-delete-forward)
(define-key evil-insert-state-map (kbd "C-n") 'auto-complete)
(define-key evil-insert-state-map (kbd "C-p") 'auto-complete)
(define-key evil-insert-state-map (kbd "C-x M-S") 'scratch-toggle)
(define-key evil-insert-state-map (kbd "C-x M-i") 'ielm-toggle)
(define-key evil-insert-state-map (kbd "<f1>") 'woman)
(define-key evil-insert-state-map (kbd "C-u") 'universal-argument)
(define-key evil-insert-state-map (kbd "C-x C-r") 'sudo-edit)

;;;;;;; Visual Map
(define-key evil-visual-state-map (kbd "C-;") 'iedit-mode)

(when (featurep 'wrap-region)
  (define-key evil-visual-state-map (kbd "<") 'wrap-region-trigger)
  (define-key evil-visual-state-map (kbd "[") 'wrap-region-trigger)
  (define-key evil-visual-state-map (kbd "{") 'wrap-region-trigger)
  (define-key evil-visual-state-map (kbd "(") 'wrap-region-trigger)
  (define-key evil-visual-state-map (kbd "'") 'wrap-region-trigger)
  (define-key evil-visual-state-map (kbd "\"") 'wrap-region-trigger)
  )

;;;;;;;; Window Map
;; (vim:wmap (kbd "C-w f") 'fullscreen-window)
;; (vim:wmap (kbd "C-w J") 'windmove-down-fullscreen)
;; (vim:wmap (kbd "C-w H") 'windmove-left-fullscreen)
;; (vim:wmap (kbd "C-w L") 'windmove-right-fullscreen)
;; (vim:wmap (kbd "C-w K") 'windmove-up-fullscreen)
;; (vim:wmap (kbd "C-w s") 'split-window)
;; (vim:wmap (kbd "C-w v") 'split-window-side-by-side)

;; (vim:wmap (kbd "C-w C-n") 'make-frame)
;; (vim:wmap (kbd "C-w C-d") 'delete-frame)
;; (vim:wmap (kbd "C-w C-o") 'other-frame)
;; (vim:wmap (kbd "C-w C-a") 'delete-other-frames)

;; (vim:wmap (kbd "C-w C-s") 'sr-speedbar-toggle)
;; (vim:wmap (kbd "C-w C-d") 'nav-toggle)



;;;;;;;; Emacs Map
(global-set-key (kbd "<f1>") 'woman)
(global-set-key (kbd "<f4>") 'shell-pop)
(global-set-key (kbd "C-x <f4>") 'switch-to-terminal)
(global-set-key (kbd "C-+") 'text-scale-increase)
(global-set-key (kbd "C--") 'text-scale-decrease)
(global-set-key (kbd "C-=") 'text-scale-increase)
(global-set-key (kbd "C-M-X") 'smex)
(global-set-key (kbd "C-c C-e") 'eval-and-replace)
(global-set-key (kbd "C-x C-b") 'ibuffer)
(global-set-key (kbd "C-x C-s") 'save-buffer-always)
(global-set-key (kbd "C-x M-l") 'egg-log)
(global-set-key (kbd "C-x M-s") 'egg-status)
(global-set-key (kbd "M-x") 'anything-M-x)
(global-set-key (kbd "C-x M-S") 'scratch-toggle)
(global-set-key (kbd "C-x M-i") 'ielm-toggle)
(global-set-key (kbd "C-x C-r") 'sudo-edit)


(provide 'coldnew-keybinding)
;; coldnew-keybinding.el ends here.
