;;
(eval-when-compile (require 'cl))

;;;;;;;; Packages Import
(require 'coldnew-macro)
(require 'coldnew-functions)
(require 'coldnew-commands)
(require 'coldnew-variables)
(require 'coldnew-evil)
(require 'coldnew-anything)
(require 'coldnew-buffer)
(require 'coldnew-project)
(require 'coldnew-editor)


;;;;;;;; Normal Map
(define-key evil-normal-state-map (kbd "C-x C-b") 'ibuffer)
;; (when (featurep 'eproject)
;;   (define-key evil-normal-state-map (kbd "C-c C-b") 'eproject-ibuffer))
(define-key evil-normal-state-map (kbd "C-x f") 'anything-find-files)
(define-key evil-normal-state-map (kbd "C-x C-f") 'lusty-file-explorer)
(define-key evil-normal-state-map (kbd "M-x") 'anything-M-x)
(define-key evil-normal-state-map (kbd "C-c C-e") 'eval-and-replace)
(define-key evil-normal-state-map (kbd "C-x C-s") 'save-buffer-always)
(define-key evil-normal-state-map (kbd "C-=") 'text-scale-increase)
(define-key evil-normal-state-map (kbd "C-+") 'text-scale-increase)
(define-key evil-normal-state-map (kbd "C--") 'text-scale-decrease)
(define-key evil-normal-state-map (kbd "<f4>") 'shell-pop)
(define-key evil-normal-state-map (kbd "<f2>") 'multi-term)
(define-key evil-normal-state-map (kbd "C-x <f4>") 'switch-to-terminal)
(define-key evil-normal-state-map (kbd "C-x M-s") 'egg-status)
(define-key evil-normal-state-map (kbd "C-x M-l") 'egg-log)
(define-key evil-normal-state-map (kbd "C-;") 'iedit-mode)
(define-key evil-normal-state-map (kbd "u")   'undo-tree-undo)
(define-key evil-normal-state-map (kbd "C-r") 'undo-tree-redo)
(define-key evil-normal-state-map (kbd "M-p") 'anything-show-kill-ring)
(define-key evil-normal-state-map (kbd "C-x M-S") 'scratch-toggle)
(define-key evil-normal-state-map (kbd "C-x M-i") 'ielm-toggle)
(define-key evil-normal-state-map (kbd "<f1>") 'woman)
(define-key evil-normal-state-map (kbd "K") 'anything-man-woman)
(define-key evil-normal-state-map (kbd "C-x C-r") 'sudo-edit)
(define-key evil-normal-state-map (kbd "M-g") 'goto-line)
(when (require* 'buffer-toggle)
  (define-key evil-normal-state-map (kbd "C-6") 'buffer-toggle))
(when (featurep 'ace-jump-mode)
  (define-key evil-normal-state-map (kbd "M-l") 'ace-jump-line-mode)
  (define-key evil-normal-state-map (kbd "M-w") 'ace-jump-word-mode)
  (define-key evil-normal-state-map (kbd "M-c") 'ace-jump-char-mode)
  (define-key evil-normal-state-map (kbd "M-f") 'ace-jump-char-smae-line-mode))

;;;;;;;; Insert Map
(define-key evil-insert-state-map (kbd "C-x C-b") 'ibuffer)
(when (featurep 'eproject)
  (define-key evil-insert-state-map (kbd "C-c C-b") 'eproject-ibuffer))
(define-key evil-insert-state-map (kbd "C-x C-f") 'lusty-file-explorer)
(define-key evil-insert-state-map (kbd "M-x") 'anything-M-x)
(define-key evil-insert-state-map (kbd "C-c C-e") 'eval-and-replace)
(define-key evil-insert-state-map (kbd "C-x C-s") 'save-buffer-always)
(define-key evil-insert-state-map (kbd "C-=") 'text-scale-increase)
(define-key evil-insert-state-map (kbd "C-+") 'text-scale-increase)
(define-key evil-insert-state-map (kbd "C--") 'text-scale-decrease)

(define-key evil-insert-state-map (kbd "C-x <f4>") 'switch-to-terminal)
(define-key evil-insert-state-map (kbd "C-x M-s") 'egg-status)
(define-key evil-insert-state-map (kbd "C-x M-l") 'egg-log)
(define-key evil-insert-state-map (kbd "<backspace>") 'hungry-delete-backward)
(define-key evil-insert-state-map (kbd "<delete>") 'hungry-delete-forward)
(define-key evil-insert-state-map (kbd "C-n") 'auto-complete)
(define-key evil-insert-state-map (kbd "C-p") 'auto-complete)
(define-key evil-insert-state-map (kbd "C-x M-S") 'scratch-toggle)
(define-key evil-insert-state-map (kbd "C-x M-i") 'ielm-toggle)
(define-key evil-insert-state-map (kbd "<f1>") 'info)
(define-key evil-insert-state-map (kbd "<f2>") 'multi-term)
(define-key evil-insert-state-map (kbd "<f3>") 'shell-pop)
(define-key evil-insert-state-map (kbd "C-u") 'universal-argument)
(define-key evil-insert-state-map (kbd "C-x C-r") 'sudo-edit)

;;;;;;; Visual Map
(when (featurep 'iedit)
  (define-key evil-visual-state-map (kbd "C-;") 'iedit-mode))
(when (featurep 'wrap-region)
  (define-key evil-visual-state-map (kbd "<") 'wrap-region-trigger)
  (define-key evil-visual-state-map (kbd "[") 'wrap-region-trigger)
  (define-key evil-visual-state-map (kbd "{") 'wrap-region-trigger)
  (define-key evil-visual-state-map (kbd "(") 'wrap-region-trigger)
  (define-key evil-visual-state-map (kbd "'") 'wrap-region-trigger)
  (define-key evil-visual-state-map (kbd "\"") 'wrap-region-trigger))

;;;;;;;; Window Map
(define-key evil-window-map  (kbd "f") 'fullscreen-window)
(define-key evil-window-map  (kbd "C-f") 'fullscreen-window)
(define-key evil-window-map  (kbd "C-j") 'windmove-down-fullscreen)
(define-key evil-window-map  (kbd "C-h") 'windmove-left-fullscreen)
(define-key evil-window-map  (kbd "C-l") 'windmove-right-fullscreen)
(define-key evil-window-map  (kbd "C-k") 'windmove-up-fullscreen)
(define-key evil-window-map  (kbd "C-v") 'split-window-vertically)
(define-key evil-window-map  (kbd "C-h") 'split-window-horizontally)
(define-key evil-window-map  (kbd "C-n") 'make-frame)
(define-key evil-window-map  (kbd "C-d") 'delete-frame)
(define-key evil-window-map  (kbd "C-o") 'other-frame)
(define-key evil-window-map  (kbd "C-a") 'delete-other-frames)
(define-key evil-window-map  (kbd "C-s") 'sr-speedbar-toggle)
(define-key evil-window-map  (kbd ".") 'winner-undo)
(define-key evil-window-map  (kbd ",") 'winner-redo)

;;;;;;;; Replace Map
(define-key evil-replace-state-map (kbd "M-l") 'downcase-word)
(define-key evil-replace-state-map (kbd "M-u") 'upcase-word)
(define-key evil-replace-state-map (kbd "M-c") 'capitalize-word)

;;;;;;;; Emacs Map
(define-key evil-emacs-state-map (kbd "C-x C-f") 'lusty-file-explorer)
(define-key evil-emacs-state-map (kbd "<f1>") 'woman)
(define-key evil-emacs-state-map (kbd "<f2>") 'multi-term)
(define-key evil-emacs-state-map (kbd "<f4>") 'shell-pop)
(define-key evil-emacs-state-map (kbd "C-x <f4>") 'switch-to-terminal)
(define-key evil-emacs-state-map (kbd "C-+") 'text-scale-increase)
(define-key evil-emacs-state-map (kbd "C--") 'text-scale-decrease)
(define-key evil-emacs-state-map (kbd "C-=") 'text-scale-increase)
(define-key evil-emacs-state-map (kbd "C-c C-e") 'eval-and-replace)
(define-key evil-emacs-state-map (kbd "C-x C-b") 'ibuffer)
(define-key evil-emacs-state-map (kbd "C-x C-s") 'save-buffer-always)
(define-key evil-emacs-state-map (kbd "C-x M-l") 'egg-log)
(define-key evil-emacs-state-map (kbd "C-x M-s") 'egg-status)
(define-key evil-emacs-state-map (kbd "M-x") 'anything-M-x)
(define-key evil-emacs-state-map (kbd "C-x M-S") 'scratch-toggle)
(define-key evil-emacs-state-map (kbd "C-x M-i") 'ielm-toggle)
(define-key evil-emacs-state-map (kbd "C-x C-r") 'sudo-edit)

;;;; Window move

(define-key evil-emacs-state-map  (kbd "C-w f") 'fullscreen-window)
(define-key evil-emacs-state-map  (kbd "C-w h") 'windmove-left)
(define-key evil-emacs-state-map  (kbd "C-w j") 'windmove-down)
(define-key evil-emacs-state-map  (kbd "C-w k") 'windmove-up)
(define-key evil-emacs-state-map  (kbd "C-w l") 'windmove-right)

(define-key evil-emacs-state-map  (kbd "C-w C-f") 'fullscreen-window)
(define-key evil-emacs-state-map  (kbd "C-w C-j") 'windmove-down-fullscreen)
(define-key evil-emacs-state-map  (kbd "C-w C-h") 'windmove-left-fullscreen)
(define-key evil-emacs-state-map  (kbd "C-w C-l") 'windmove-right-fullscreen)
(define-key evil-emacs-state-map  (kbd "C-w C-k") 'windmove-up-fullscreen)
(define-key evil-emacs-state-map  (kbd "C-w C-v") 'split-window-vertically)
(define-key evil-emacs-state-map  (kbd "C-w C-h") 'split-window-horizontally)
(define-key evil-emacs-state-map  (kbd "C-w C-n") 'make-frame)
(define-key evil-emacs-state-map  (kbd "C-w C-d") 'delete-frame)
(define-key evil-emacs-state-map  (kbd "C-w C-o") 'other-frame)
(define-key evil-emacs-state-map  (kbd "C-w C-a") 'delete-other-frames)
(define-key evil-emacs-state-map  (kbd "C-w C-s") 'sr-speedbar-toggle)
(define-key evil-emacs-state-map  (kbd "C-w .") 'winner-undo)
(define-key evil-emacs-state-map  (kbd "C-w ,") 'winner-redo)


(global-set-key (kbd "C-x C-f") 'lusty-file-explorer)



(provide 'coldnew-keybinding)
;; coldnew-keybinding.el ends here.
