#!/bin/sh
# mptest -- script to process a single picture file through MetaPost
#           to produce an eps file
#
# Usage: ./mptest file
#
# e.g. copy ex01.m4 here and type ./mptest ex01
# Starting with file.m4, invoke m4, dpic -s, MetaPost

LIBS="$HOME/lib/mpost.m4 $HOME/lib/libcct.m4 $HOME/lib/liblog.m4"

rm -f $1.ps F$1.* $1.1 $1.mp $1.pic
m4 -B32000 $LIBS $1.m4 > $1.pic

# Write the LaTeX heading.  The = signs get translated to backslashes
#
( echo 'verbatimtex
=documentclass[11pt]{article}
=usepackage{times,boxdims}=usepackage{graphicx}
=begin{document} etex
') | tr '=' '\134' > $1.mp

dpic -s $1.pic >> $1.mp

TEX=latex mpost $1.mp end
