#+TITLE: Editorconfig Integrate Setup
#+AUTHOR: Yen-Chin, Lee <coldnew>
#+email: coldnew.tw at gmail.com
#+DESCRIPTION: Integrate Editorconfig with coldnew's emacs

#+SETUPFILE: configs.setup

[[http://editorconfig.org][Editorconfig]] helps developers define and maintain consistent coding styles between different editors and IDEs.
The EditorConfig project consists of a file format for defining coding styles and a collection of text editor plugins that enable editors to read the file format and adhere to defined styles. EditorConfig files are easily readable and they work nicely with version control systems.

GitHub: https://github.com/editorconfig/editorconfig-emacs

* Install libraries

To install these libraries, you only need to use =M-x package-install= command.

#+BEGIN_SRC emacs-lisp
  (package-install 'editorconfig)
#+END_SRC

* Install System packages

Download the [[https://github.com/editorconfig/editorconfig-core-c][EditorConfig C Core]] and follow the instructions in the README and INSTALL files to install it.

This plugin also has a core library implemented in Emacs-Lisp, and fallback to it when no core executable is found.

You also can use OS's package manager to install it

** Mac OSX

#+BEGIN_SRC sh  :tangle no :noweb-ref install-in-macosx
  brew install editorconfig
#+END_SRC

** Gentoo Linux

I write a ebuild for editorconfig [[https://github.com/coldnew/coldnew-overlay/tree/master/app-editors/editorconfig][here]].

#+BEGIN_SRC emacs-lisp :tangle no :noweb-ref install-in-gentoo
  emerge app-editors/editorconfig
#+END_SRC

* Core package setup

#+BEGIN_SRC emacs-lisp :noweb no-export :exports code
  (use-package editorconfig
    :init
    (add-hook 'prog-mode-hook (editorconfig-mode 1))
    (add-hook 'text-mode-hook (editorconfig-mode 1)))
#+END_SRC
* End of configuration

#+BEGIN_SRC emacs-lisp
  (provide 'configs/plugins/editorconfig)
#+END_SRC
